import { Inter } from 'next/font/google'
import './globals.css'
import Nav from './components/Nav'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning={true} lang="en">
      <body>
        <Nav></Nav>
        {children}
        </body>
    </html>
  )
}
